### PR TITLE
Move furthermost events to the cluster centroid for better DD relocation

### PR DESCRIPTION
**Pull request by nlanget**
- Main changes are in double_diff.py: similar events which are too far from the centroid are relocated to the centroid. It works much better for most crises. I still have some trouble for the crisis of the 29th october 2010 and I don't know why, but I'm going to have a look at it.
- I also made minor changes in SDS_processing.py: filenames are directly read from the option dictionary.
- in locations_trigger.py: the program keeps running even though data are missing.

@amaggi

### CODE REVIEW

**Comment by nlanget** [comment]
- I  have finally found out why the relocation was not working well for the  crisis of 29th october. The problem was a clustering problem. I've fixed it.
- I've also added a test for clustering.
  @amaggi

**Comment by amaggi** [comment]
Can you please run the tests to make sure everything works on your machine.  When I ran it on both the mac at the office and my laptop I got two errors.  One was a mayavi import that can probably be fixed by a conditional import (if mayavi is installed then load it). If you only use mayavi for plotting stuff, then we can find some work-around to create less beautiful plots if mayavi is not available...  The other was a real error:

```
======================================================================
ERROR: test_locations_trigger (test_location.LocationTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/alessia/Documents/working/waveloc/PyProgs/test/test_location.py", line 163, in test_locations_trigger
    do_locations_trigger_setup_and_run(self.wo.opdict)
  File "/Users/alessia/Documents/working/waveloc/PyProgs/locations_trigger.py", line 289, in do_locations_trigger_setup_and_run
    if number_good_kurtosis_for_location(kurt_files,data_files,loc,time_grids,snr_limit,snr_tr_limit,sn_time) > n_kurt_min:
  File "/Users/alessia/Documents/working/waveloc/PyProgs/locations_trigger.py", line 68, in number_good_kurtosis_for_location
    dfilename=data_files[ifile]
IndexError: list index out of range
```

Also, you should call you test_clustering code from test_waveloc (see existing calls to see how it is done)... Thank you! (and do not import mayavi unless it is absolutely necessary for the test - not everyone will have mayavi)

**Comment by nlanget** [comment]
- I've moved import mayavi inside the plotting function
- the error in test_location was only due to the fact that we created new files in data/TEST instead of replacing the older ones (there were twice as many kurtfiles as datafiles). So I've just changed the names in the test_option dictionnary and removed the bad files in data/TEST. Now it works fine.
- I've also fixed a small error in double_diff
- I've added test_clustering to the test suite in test_waveloc

**Comment by amaggi** [comment]
OK.  I'll merge

**Pull request merged**
