### PR TITLE
Modified locations_trigger

### PR DESCRIPTION
**Pull request by nlanget**
- traces are now aligned on the first arrival for SNR computation
- I have added a kind of header for the location file. I don't know if it is really useful, but we can easily get lost when trying different parameters... I haven't modified test_location.py yet.

### CODE REVIEW

**Comment by amaggi** [comment]
For your location header, a cleaner way of coding it would be to add a # with a space in front of any 'comment' or 'header' lines, and change your 

```
if nb_line >= 5:
```

to

```
if line.split()[0]=='#':
```

This will allow you to add as may header or comment lines to the locations file as you like.

**Comment by nlanget** [comment]
Modification done !

**Comment by amaggi** [comment]
And you even fixed my buggy suggestion ;-)

**Comment by amaggi** [comment]
... but it broke the test.  The problem was with the empty line you now add to the locations file.
As having empty lines is not a bad idea, change the if statement to:

```
 if not line.isspace() and line[0] != '#':
```

(I tested this on my system before suggesting it this time)

**Comment by nlanget** [comment]
Indeed...
I have corrected it.

**Pull request merged**
