### PR TITLE
Small changes in OP_waveforms.py

### PR DESCRIPTION
**Pull request by nlanget**
- gauss option: the whole trace was shifted by one time sample. I fixed it. 
- grad: now takes into account the sampling frequency 
- using sw_kurtosis2 takes too much memory... I haven't found the cause of the problem yet... It is better to use  sw_kurtosis1 at the moment.

@amaggi

### CODE REVIEW

**Comment by amaggi** [comment]
@nlanget 
I know why sw_kurtosis2 uses more memory : it puts each separate window as a row in a numpy 2D array and then runs the kurtosis on the whole array in one step.  The actual kurtosis calculation is faster, but it needs more memory.

I'll do some profiling to check memory usage, and fix it in the same way as the migration (dynamic chunking of the data according to memory availability).  I've created an issue (#50) to deal with this.  Using `sw_kurtosis1` for now is just fine.

**Comment by amaggi** [comment]
@nlanget You don't need to pass `dt` to `stream_positive_derivative` because each trace knows what its `dt` is.  Simply change the function to get `dt` as follows:

```
for tr in st:
     xs=tr.data
     dt=tr.stats.delta
```

**Comment by amaggi** [comment]
@nlanget 
Thanks for putting the sampling frequency into the gradient !!  I've written an analytic test which runs correctly for your function.  I'll put it into the code as soon as you make the `dt` modification in my previous comment.

**Comment by nlanget** [comment]
Modification done !

**Pull request merged**
